### PR TITLE
Improve GNUMake detection at build time

### PR DESCRIPTION
**Pull request by ke6jjj**

### CODE REVIEW

**Comment by ke6jjj** [comment]
The changelog looks hilarious but really there are just a couple of lines changing here in the end.

**Comment by JayKickliter** [comment]
Thanks! I _think_ the whole PR could be a one line change of calling `cmake --build build --parallel` instead of manually figuring out which make variant to use, or did you already try that?

**Comment by ke6jjj** [comment]
I didn't try that, will do now!

**Comment by ke6jjj** [comment]
will add `--parallel` (saw edit)

**Comment by JayKickliter** [comment]
I just realized something. For some reason lost to time, the ugly truth is that miner is not using the master branch of this repo. Instead, it's been using the head of this branch https://github.com/helium/longfi-erlang/pull/2. I'm not sure how to proceed. I guess we should just merge that branch and maybe apply this patch on top of that if even still needed.  I'm sorry about this, this library is in maintenance mode only and I guess it got forgotten about.

**Comment by ke6jjj** [comment]
That's accounted for, check the destination branch of this PR.

**Comment by JayKickliter** [comment]
Ah, very good! Yeah, let's merge this and _then_ merge that other branch.

**Comment by ke6jjj** [comment]
Suggested changes worked-on-my-box!

**Comment by ke6jjj** [comment]
Hey @JayKickliter , do you think you can update `rebar.config` in the miner now? It's still referring to the old branch, and I think miner builds are broken as a result. 😅

**Pull request merged**
